package com.example.vpn

data class VpnServer(
    val id: String,
    val countryName: String,
    val countryNameAr: String,
    val city: String,
    val cityAr: String,
    val flagEmoji: String,
    val host: String,
    val port: Int,
    val dnsServer: String = "1.1.1.1",
    val secondaryDns: String = "1.0.0.1",
    val pingMs: Int = -1,
    val loadPercent: Int = 35,
    val protocol: String = "SSH",
    val isCustom: Boolean = false,
    val rawConfig: String? = null,
    val extraParams: Map<String, String> = emptyMap(),
    val username: String = "",
    val password: String = "",
    val category: String = "GCP", // "GCP", "SSH", "V2RAY", "CUSTOM"
    val sniHost: String = "",     // e.g. "youtube.com" (Bug Host / SNI Spoof)
    val payload: String = "",     // Custom HTTP / WebSocket payload
    val proxyHost: String = "",   // Proxy host IP
    val proxyPort: Int = 0,       // Proxy port (e.g. 80, 8080, 3128)
    val notes: String = ""        // Additional notes
) {
    companion object {
        val DEFAULT_SERVERS = listOf(
            // Google Cloud Platform Servers
            VpnServer(
                id = "gcp_youtube_sim",
                countryName = "Google Cloud (YouTube Pack)",
                countryNameAr = "قوقل كلاود - عرض يوتيوب للشريحة",
                city = "Google Cloud VM",
                cityAr = "📺 سيرفر Google Cloud (عرض YouTube)",
                flagEmoji = "📺",
                host = "8.8.8.8",
                port = 443,
                dnsServer = "8.8.8.8",
                secondaryDns = "8.8.4.4",
                pingMs = 28,
                loadPercent = 22,
                protocol = "SSH",
                category = "GCP",
                sniHost = "youtube.com",
                username = "admin",
                password = "",
                notes = "معد خصيصاً للشريحة التي تحتوي على عرض YouTube"
            ),
            VpnServer(
                id = "gcp_us_central",
                countryName = "Google Cloud (US Central)",
                countryNameAr = "قوقل كلاود - أمريكا (us-central1)",
                city = "Council Bluffs VM",
                cityAr = "سيرفر Google Cloud (Iowa)",
                flagEmoji = "🌐",
                host = "8.8.8.8",
                port = 53,
                dnsServer = "8.8.8.8",
                secondaryDns = "8.8.4.4",
                pingMs = 28,
                loadPercent = 25,
                protocol = "SSH",
                category = "GCP",
                username = "gcp-user",
                password = "",
                rawConfig = "ssh://gcp-user@8.8.8.8:53#Google-Cloud-US"
            ),
            VpnServer(
                id = "gcp_eu_west",
                countryName = "Google Cloud (Europe West)",
                countryNameAr = "قوقل كلاود - أوروبا (europe-west3)",
                city = "Frankfurt GCP Node",
                cityAr = "سيرفر Google Cloud (فرانكفورت)",
                flagEmoji = "🌐",
                host = "1.1.1.1",
                port = 443,
                dnsServer = "8.8.8.8",
                secondaryDns = "1.1.1.1",
                pingMs = 36,
                loadPercent = 32,
                protocol = "VLESS",
                category = "GCP",
                sniHost = "youtube.com",
                rawConfig = "vless://gcp-eu@1.1.1.1:443?type=ws&security=tls#Google-Cloud-Frankfurt"
            ),
            VpnServer(
                id = "gcp_asia_east",
                countryName = "Google Cloud (Asia East)",
                countryNameAr = "قوقل كلاود - آسيا (asia-east1)",
                city = "Tokyo GCP Cloud",
                cityAr = "سيرفر Google Cloud (طوكيو)",
                flagEmoji = "🌐",
                host = "8.8.4.4",
                port = 53,
                dnsServer = "8.8.8.8",
                secondaryDns = "8.8.4.4",
                pingMs = 45,
                loadPercent = 30,
                protocol = "SSH",
                category = "GCP",
                username = "gcp-asia",
                password = ""
            ),

            // SSH / BHTTP Category (Matches Screenshot 1 & 2)
            VpnServer(
                id = "ssh_ocean_proxy",
                countryName = "SSHOcean (Proxy + Payload)",
                countryNameAr = "سيرفر SSHOcean (بروكسي + بايلود)",
                city = "Squid Proxy Tunnel",
                cityAr = "📺 SSHOcean بروكسي + بايلود يوتيوب",
                flagEmoji = "⚡",
                host = "1.1.1.1",
                port = 22,
                dnsServer = "1.1.1.1",
                secondaryDns = "8.8.8.8",
                pingMs = 35,
                loadPercent = 25,
                protocol = "SSH + PROXY",
                category = "SSH",
                sniHost = "youtube.com",
                proxyHost = "1.1.1.1",
                proxyPort = 8080,
                payload = "GET / HTTP/1.1[crlf]Host: youtube.com[crlf]Upgrade: websocket[crlf]Connection: Upgrade[crlf][crlf]",
                username = "sshocean",
                password = "",
                notes = "سيرفر SSH مع بروكسي سكويد وبايلود ثغرة يوتيوب للشريحة"
            ),
            VpnServer(
                id = "ssh_bhttp_vivo",
                countryName = "BHTTP SSH Tunnel",
                countryNameAr = "BHTTP VIVO,TIM,CLARO - SSH_BHTTP",
                city = "Direct SSL Payload",
                cityAr = "نفق SSH مباشر مع بايلود",
                flagEmoji = "⚡",
                host = "1.0.0.1",
                port = 22,
                dnsServer = "1.1.1.1",
                secondaryDns = "1.0.0.1",
                pingMs = 52,
                loadPercent = 48,
                protocol = "SSH",
                category = "SSH",
                sniHost = "m.youtube.com",
                username = "test_user",
                password = ""
            ),
            VpnServer(
                id = "ssh_direct_ssl",
                countryName = "SSL / SSH Direct",
                countryNameAr = "SSH Direct SSL / TLS 443",
                city = "Secure Tunnel",
                cityAr = "اتصال SSH مباشر 443",
                flagEmoji = "🟣",
                host = "1.1.1.1",
                port = 443,
                dnsServer = "1.1.1.1",
                secondaryDns = "8.8.8.8",
                pingMs = 41,
                loadPercent = 35,
                protocol = "SSH",
                category = "SSH",
                sniHost = "youtube.com",
                username = "client",
                password = ""
            ),

            // V2Ray / Xray Category (Matches Screenshot 2)
            VpnServer(
                id = "tim_xray_01",
                countryName = "TIM XRAY [01]",
                countryNameAr = "TIM XRAY VÁLIDO E EXPIRADO",
                city = "V2RAY/XRAY - VLESS",
                cityAr = "سيرفر VLESS مضاد للحجب",
                flagEmoji = "⚡",
                host = "1.1.1.1",
                port = 443,
                dnsServer = "1.1.1.1",
                secondaryDns = "1.0.0.1",
                pingMs = 38,
                loadPercent = 29,
                protocol = "VLESS",
                category = "V2RAY",
                sniHost = "youtube.com",
                rawConfig = "vless://tim-xray@1.1.1.1:443?type=ws&security=tls#TIM-XRAY-01",
                extraParams = mapOf("security" to "tls", "type" to "ws")
            ),
            VpnServer(
                id = "vmess_shield_02",
                countryName = "Cloudflare VMess",
                countryNameAr = "TIM CLOUDFLAR€ - VMess CDN",
                city = "VMess WebSocket",
                cityAr = "سيرفر VMess CDN السريع",
                flagEmoji = "🔵",
                host = "9.9.9.9",
                port = 443,
                dnsServer = "9.9.9.9",
                secondaryDns = "1.1.1.1",
                pingMs = 44,
                loadPercent = 40,
                protocol = "VMESS",
                category = "V2RAY",
                rawConfig = "vmess://eyJaddIjoiOS45LjkuOSIsInBvcnQiOjQ0MywicHMiOiJDT1VELVZNRVNTIn0=",
                extraParams = mapOf("tls" to "tls", "net" to "ws")
            )
        )
    }
}
